name: archethic_wallet_client
description: A client dart library to interact with Archethic Wallet RPC API.
version: 1.2.2
homepage: https://github.com/archethic-foundation/archethic-wallet-client-dart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Archethic dart library for Flutter
  archethic_lib_dart: ^3.3.0

  # A RPC-via-deeplink communication library coded in Dart. This is dedicated to Flutter mobile applications (iOS / Android).
  deeplink_rpc: ^1.0.6

  flutter:
    sdk: flutter

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.4.1

  # Annotations to create static Dart interfaces for JavaScript APIs.
  js: ^0.6.7

  # Annotations for the JsonSerializable code-generator.
  json_annotation: ^4.8.1

  # JSON-RPC (v2.0) utility classes. Invoke methods on another machine using JSON-formatted messages. Some assembly required.
  json_rpc_2: ^3.0.2

  # An abstraction for two-way communication channels based on the Dart Stream class.
  stream_channel: ^2.1.2

  # StreamChannel wrappers for WebSockets. Provides a cross-platform WebSocketChannel API, a cross-platform implementation of that API that communicates over an underlying StreamChannel.
  web_socket_channel: ^2.4.0

dev_dependencies:
  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.6

  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  dependency_validator: ^3.0.0

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1

  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.5
