name: libdart_dapp
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

publish_to: none # TODO(Chralu): remove

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
  

dependencies:
  archethic_lib_dart: ^3.0.0
  deeplink_rpc:  # TODO(Chralu): use pub.dev library
    git: 
      url: https://github.com/archethic-foundation/lib-deeplink-rpc.git
      ref: main

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^2.2.0
