name: archethic_wallet_client
description: A client dart library to interact with Archethic Wallet RPC API.
version: 1.0.6
homepage: https://github.com/archethic-foundation/archethic-wallet-client-dart

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  # Archethic dart library for Flutter
  #archethic_lib_dart: ^3.2.0
  archethic_lib_dart:
    git:
      url: https://github.com/archethic-foundation/libdart.git
      ref: dev

  # A RPC-via-deeplink communication library coded in Dart. This is dedicated to Flutter mobile applications (iOS / Android).
  deeplink_rpc: ^1.0.5

  flutter:
    sdk: flutter

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.4.1

  # Annotations for the JsonSerializable code-generator.
  json_annotation: ^4.8.1

  # JSON-RPC (v2.0) utility classes. Invoke methods on another machine using JSON-formatted messages. Some assembly required.
  json_rpc_2: ^3.0.2

  # StreamChannel wrappers for WebSockets. Provides a cross-platform WebSocketChannel API, a cross-platform implementation of that API that communicates over an underlying StreamChannel.
  web_socket_channel: ^2.4.0

dev_dependencies:
  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.6

  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  dependency_validator: ^3.0.0

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.2

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1

  # Official Dart lint rules. Defines the 'core' and 'recommended' set of lints suggested by the Dart team
  lints: ^2.0.2

  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.5
